apiVersion: v1
kind: Service
metadata:
  name: tcp-echo
  labels:
    app: tcp-echo
spec:
  selector:
    app: tcp-echo
  ports:
    - name: tcp-echo
      port: 9095
      targetPort: 9095
      protocol: TCP
  type: ClusterIP
